import path from 'node:path'
const D = path.resolve('live/admin/b')
export default async ({ page, admin, base, shot, log, problems, api, b }) => {
  await page.goto(`${admin}/settings?tab=basic`); await page.waitForLoadState('networkidle')
  await page.getByRole('button', { name: '选择/上传' }).click(); await page.waitForTimeout(800)
  let dlg = page.locator('[role=dialog]').last()
  await dlg.getByText('qa-favicon').first().click()
  await dlg.getByRole('button', { name: '确认选择' }).click(); await page.waitForTimeout(500)
  await page.getByRole('button', { name: '选择 Logo' }).click(); await page.waitForTimeout(800)
  dlg = page.locator('[role=dialog]').last()
  await dlg.getByText('上传新文件').click(); await page.waitForTimeout(300)
  await dlg.locator('input[type=file]').first().setInputFiles(path.join(D, 'qa-logo.png')); await page.waitForTimeout(2500)
  await shot(page, 'b-020-logo-upload', false)
  await dlg.getByRole('button', { name: '确认选择' }).click().catch(e => log('no confirm', e.message.slice(0, 80))); await page.waitForTimeout(500)
  await page.getByRole('button', { name: '新增链接' }).click(); await page.waitForTimeout(300)
  const inputs = page.locator('xpath=//*[contains(text(),"页脚自定义链接")]/ancestor::section[1]//input | //*[contains(text(),"页脚自定义链接")]/ancestor::div[contains(@class,"rounded")][1]//input')
  log('footer inputs', await inputs.count())
  await inputs.nth(0).fill('QA备案号'); await inputs.nth(1).fill('https://example.com/qa')
  await shot(page, 'b-020-before-save2')
  await page.getByTestId('settings-save').click(); await page.waitForTimeout(2000)
  const sc = await api('GET', '/admin/settings?key=site_config'); log('brand', JSON.stringify(sc.data.brand), JSON.stringify(sc.data.footer_links))
  const sp = await page.context().newPage()
  await sp.goto(base + '/'); await sp.waitForLoadState('networkidle'); await sp.waitForTimeout(1000)
  const sf = await sp.evaluate(() => ({ title: document.title, icon: [...document.querySelectorAll('link[rel*=icon]')].map(l => l.href), imgs: [...document.querySelectorAll('header img, footer img')].map(i => i.src), footer: document.querySelector('footer')?.innerText.slice(0, 400) }))
  log('storefront', JSON.stringify(sf))
  await shot(sp, 'b-020-storefront2', false)
  const lp = await b.newPage(); await lp.goto(admin + '/login'); await lp.waitForLoadState('networkidle'); await lp.waitForTimeout(800)
  log('admin login', JSON.stringify(await lp.evaluate(() => ({ imgs: [...document.querySelectorAll('img')].map(i => i.src), icon: [...document.querySelectorAll('link[rel*=icon]')].map(l => l.href) }))))
  await shot(lp, 'b-020-admin-login2', false)
}
