//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "admin_login_logs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(indexed)]
    pub admin_id: i64,
    #[sea_orm(column_type = "String(StringLen::N(255))", indexed)]
    pub username: String,
    #[sea_orm(column_type = "String(StringLen::N(40))", indexed)]
    pub event_type: String,
    #[sea_orm(column_type = "String(StringLen::N(255))", indexed)]
    pub status: String,
    #[sea_orm(column_type = "String(StringLen::N(255))", indexed)]
    pub fail_reason: String,
    #[sea_orm(column_type = "String(StringLen::N(64))", indexed)]
    pub client_ip: String,
    #[sea_orm(column_type = "Text")]
    pub user_agent: String,
    #[sea_orm(column_type = "String(StringLen::N(64))", indexed)]
    pub request_id: String,
    #[sea_orm(indexed, nullable)]
    pub operator_id: Option<i64>,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
