//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "affiliate_commissions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "idx_affiliate_commission_unique", indexed)]
    pub affiliate_profile_id: i64,
    #[sea_orm(unique_key = "idx_affiliate_commission_unique", indexed)]
    pub order_id: i64,
    #[sea_orm(indexed, nullable)]
    pub order_item_id: Option<i64>,
    #[sea_orm(
        column_type = "String(StringLen::N(20))",
        unique_key = "idx_affiliate_commission_unique",
        default_value = "order"
    )]
    pub commission_type: String,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub base_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub rate_percent: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub commission_amount: Decimal,
    #[sea_orm(column_type = "String(StringLen::N(32))", indexed)]
    pub status: String,
    #[sea_orm(indexed, nullable)]
    pub confirm_at: Option<DateTimeUtc>,
    #[sea_orm(indexed, nullable)]
    pub available_at: Option<DateTimeUtc>,
    #[sea_orm(indexed, nullable)]
    pub withdraw_request_id: Option<i64>,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub invalid_reason: String,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
