//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "affiliate_withdraw_requests")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(indexed)]
    pub affiliate_profile_id: i64,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub amount: Decimal,
    #[sea_orm(column_type = "String(StringLen::N(50))")]
    pub channel: String,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub account: String,
    #[sea_orm(column_type = "String(StringLen::N(32))", indexed)]
    pub status: String,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub reject_reason: String,
    #[sea_orm(indexed, nullable)]
    pub processed_by: Option<i64>,
    #[sea_orm(indexed, nullable)]
    pub processed_at: Option<DateTimeUtc>,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
