//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "affiliate_clicks")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(indexed)]
    pub affiliate_profile_id: i64,
    #[sea_orm(column_type = "String(StringLen::N(128))", indexed)]
    pub visitor_key: String,
    #[sea_orm(column_type = "String(StringLen::N(512))")]
    pub landing_path: String,
    #[sea_orm(column_type = "String(StringLen::N(1024))")]
    pub referrer: String,
    #[sea_orm(column_type = "String(StringLen::N(64))")]
    pub client_ip: String,
    #[sea_orm(column_type = "String(StringLen::N(1024))")]
    pub user_agent: String,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
