//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "api_credentials")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub user_id: i64,
    #[sea_orm(column_type = "String(StringLen::N(64))", unique)]
    pub api_key: String,
    #[sea_orm(column_type = "String(StringLen::N(256))")]
    pub api_secret: String,
    #[sea_orm(
        column_type = "String(StringLen::N(20))",
        default_value = "pending_review"
    )]
    pub status: String,
    #[sea_orm(column_type = "String(StringLen::N(500))")]
    pub reject_reason: String,
    #[sea_orm(nullable)]
    pub approved_at: Option<DateTimeUtc>,
    #[sea_orm(default_value = false)]
    pub is_active: bool,
    #[sea_orm(nullable)]
    pub last_used_at: Option<DateTimeUtc>,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
