//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "authz_audit_logs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(indexed)]
    pub operator_admin_id: i64,
    #[sea_orm(column_type = "String(StringLen::N(100))", indexed)]
    pub operator_username: String,
    #[sea_orm(indexed, nullable)]
    pub target_admin_id: Option<i64>,
    #[sea_orm(column_type = "String(StringLen::N(100))", indexed)]
    pub target_username: String,
    #[sea_orm(column_type = "String(StringLen::N(100))", indexed)]
    pub action: String,
    #[sea_orm(column_type = "String(StringLen::N(120))", indexed)]
    pub role: String,
    #[sea_orm(column_type = "String(StringLen::N(255))", indexed)]
    pub object: String,
    #[sea_orm(column_type = "String(StringLen::N(20))", indexed)]
    pub method: String,
    #[sea_orm(column_type = "String(StringLen::N(64))", indexed)]
    pub request_id: String,
    #[sea_orm(column_type = "Json", nullable)]
    pub detail_json: Option<Json>,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
