//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "banners")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "String(StringLen::N(120))", indexed)]
    pub name: String,
    #[sea_orm(column_type = "String(StringLen::N(60))", indexed)]
    pub position: String,
    #[sea_orm(column_type = "Json", nullable)]
    pub title_json: Option<Json>,
    #[sea_orm(column_type = "Json", nullable)]
    pub subtitle_json: Option<Json>,
    #[sea_orm(column_type = "String(StringLen::N(500))")]
    pub image: String,
    #[sea_orm(column_type = "String(StringLen::N(500))")]
    pub mobile_image: String,
    #[sea_orm(column_type = "String(StringLen::N(20))", default_value = "none")]
    pub link_type: String,
    #[sea_orm(column_type = "String(StringLen::N(1000))")]
    pub link_value: String,
    #[sea_orm(default_value = false)]
    pub open_in_new_tab: bool,
    #[sea_orm(indexed, default_value = true)]
    pub is_active: bool,
    #[sea_orm(indexed, nullable)]
    pub start_at: Option<DateTimeUtc>,
    #[sea_orm(indexed, nullable)]
    pub end_at: Option<DateTimeUtc>,
    #[sea_orm(indexed, default_value = 0)]
    pub sort_order: i32,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
