//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "card_secrets")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub product_id: i64,
    #[sea_orm(default_value = 0)]
    pub sku_id: i64,
    #[sea_orm(indexed, nullable)]
    pub batch_id: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub secret: String,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub status: String,
    #[sea_orm(indexed, nullable)]
    pub order_id: Option<i64>,
    #[sea_orm(indexed, nullable)]
    pub reserved_at: Option<DateTimeUtc>,
    #[sea_orm(indexed, nullable)]
    pub used_at: Option<DateTimeUtc>,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
