//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "card_secret_batches")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(indexed)]
    pub product_id: i64,
    #[sea_orm(indexed, default_value = 0)]
    pub sku_id: i64,
    #[sea_orm(column_type = "String(StringLen::N(255))", unique)]
    pub batch_no: String,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub source: String,
    pub total_count: i32,
    #[sea_orm(column_type = "Text")]
    pub note: String,
    #[sea_orm(indexed, nullable)]
    pub created_by: Option<i64>,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
