//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "cart_items")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "idx_cart_user_product_sku")]
    pub user_id: i64,
    #[sea_orm(unique_key = "idx_cart_user_product_sku")]
    pub product_id: i64,
    #[sea_orm(unique_key = "idx_cart_user_product_sku", default_value = 0)]
    pub sku_id: i64,
    pub quantity: i32,
    #[sea_orm(column_type = "String(StringLen::N(20))", default_value = "manual")]
    pub fulfillment_type: String,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
