//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "channel_clients")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "String(StringLen::N(100))")]
    pub name: String,
    #[sea_orm(column_type = "String(StringLen::N(50))", indexed)]
    pub channel_type: String,
    #[sea_orm(column_type = "String(StringLen::N(64))", unique)]
    pub channel_key: String,
    #[sea_orm(column_type = "String(StringLen::N(512))")]
    pub channel_secret: String,
    #[sea_orm(column_type = "String(StringLen::N(512))")]
    pub bot_token: String,
    #[sea_orm(column_type = "String(StringLen::N(500))")]
    pub callback_url: String,
    #[sea_orm(indexed, default_value = 1)]
    pub status: i32,
    #[sea_orm(column_type = "String(StringLen::N(500))")]
    pub description: String,
    #[sea_orm(nullable)]
    pub last_used_at: Option<DateTimeUtc>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
