//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "coupons")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "String(StringLen::N(255))", unique)]
    pub code: String,
    #[sea_orm(column_type = "String(StringLen::N(255))", column_name = "type")]
    pub type_: String,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub value: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub min_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub max_discount: Decimal,
    #[sea_orm(default_value = 0)]
    pub usage_limit: i32,
    #[sea_orm(default_value = 0)]
    pub used_count: i32,
    #[sea_orm(default_value = 0)]
    pub per_user_limit: i32,
    #[sea_orm(default_value = false)]
    pub disabled_wholesale_price: bool,
    #[sea_orm(default_value = false)]
    pub per_item_discount: bool,
    #[sea_orm(column_type = "Json", nullable)]
    pub payment_roles: Option<Json>,
    #[sea_orm(column_type = "Json", nullable)]
    pub member_levels: Option<Json>,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub scope_type: String,
    #[sea_orm(column_type = "Text")]
    pub scope_ref_ids: String,
    #[sea_orm(indexed, nullable)]
    pub starts_at: Option<DateTimeUtc>,
    #[sea_orm(indexed, nullable)]
    pub ends_at: Option<DateTimeUtc>,
    #[sea_orm(default_value = true)]
    pub is_active: bool,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
