//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "downstream_order_refs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub order_id: i64,
    #[sea_orm(indexed)]
    pub api_credential_id: i64,
    #[sea_orm(column_type = "String(StringLen::N(64))", indexed)]
    pub downstream_order_no: String,
    #[sea_orm(column_type = "String(StringLen::N(500))")]
    pub callback_url: String,
    #[sea_orm(column_type = "String(StringLen::N(64))", indexed)]
    pub trace_id: String,
    #[sea_orm(column_type = "String(StringLen::N(20))", default_value = "pending")]
    pub callback_status: String,
    #[sea_orm(default_value = 0)]
    pub callback_retry_count: i32,
    #[sea_orm(nullable)]
    pub last_callback_at: Option<DateTimeUtc>,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
