//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "email_verify_codes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "String(StringLen::N(255))", indexed)]
    pub email: String,
    #[sea_orm(indexed, nullable)]
    pub user_id: Option<i64>,
    #[sea_orm(column_type = "String(StringLen::N(255))", indexed)]
    pub purpose: String,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub code: String,
    #[sea_orm(indexed)]
    pub expires_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub verified_at: Option<DateTimeUtc>,
    #[sea_orm(default_value = 0)]
    pub attempt_count: i32,
    #[sea_orm(indexed)]
    pub sent_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
