//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "fulfillments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub order_id: i64,
    #[sea_orm(column_type = "String(StringLen::N(255))", column_name = "type")]
    pub type_: String,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub status: String,
    #[sea_orm(column_type = "Text")]
    pub payload: String,
    #[sea_orm(column_type = "Json", nullable)]
    pub logistics_json: Option<Json>,
    #[sea_orm(indexed, nullable)]
    pub delivered_by: Option<i64>,
    #[sea_orm(indexed, nullable)]
    pub delivered_at: Option<DateTimeUtc>,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
