//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "gift_cards")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(indexed, nullable)]
    pub batch_id: Option<i64>,
    #[sea_orm(column_type = "String(StringLen::N(120))")]
    pub name: String,
    #[sea_orm(column_type = "String(StringLen::N(80))", unique)]
    pub code: String,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub amount: Decimal,
    #[sea_orm(column_type = "String(StringLen::N(16))", default_value = "CNY")]
    pub currency: String,
    #[sea_orm(
        column_type = "String(StringLen::N(24))",
        indexed,
        default_value = "active"
    )]
    pub status: String,
    #[sea_orm(indexed, nullable)]
    pub expires_at: Option<DateTimeUtc>,
    #[sea_orm(indexed, nullable)]
    pub redeemed_at: Option<DateTimeUtc>,
    #[sea_orm(indexed, nullable)]
    pub redeemed_user_id: Option<i64>,
    #[sea_orm(indexed, nullable)]
    pub wallet_txn_id: Option<i64>,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
