//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "media")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "String(StringLen::N(255))", indexed)]
    pub name: String,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub filename: String,
    #[sea_orm(column_type = "String(StringLen::N(500))", unique)]
    pub path: String,
    #[sea_orm(column_type = "String(StringLen::N(100))")]
    pub mime_type: String,
    pub size: i64,
    #[sea_orm(column_type = "String(StringLen::N(60))", indexed)]
    pub scene: String,
    #[sea_orm(default_value = 0)]
    pub width: i32,
    #[sea_orm(default_value = 0)]
    pub height: i32,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
