//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "member_level_prices")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "idx_member_level_price")]
    pub member_level_id: i64,
    #[sea_orm(unique_key = "idx_member_level_price")]
    pub product_id: i64,
    #[sea_orm(unique_key = "idx_member_level_price", default_value = 0)]
    pub sku_id: i64,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub price_amount: Decimal,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
