//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "notification_logs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "String(StringLen::N(100))", indexed)]
    pub event_type: String,
    #[sea_orm(column_type = "String(StringLen::N(100))", indexed)]
    pub biz_type: String,
    #[sea_orm(indexed, default_value = 0)]
    pub biz_id: i64,
    #[sea_orm(column_type = "String(StringLen::N(32))", indexed)]
    pub channel: String,
    #[sea_orm(column_type = "String(StringLen::N(255))", indexed)]
    pub recipient: String,
    #[sea_orm(column_type = "String(StringLen::N(20))", indexed)]
    pub locale: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub body: String,
    #[sea_orm(column_type = "String(StringLen::N(32))", indexed)]
    pub status: String,
    #[sea_orm(column_type = "Text")]
    pub error_message: String,
    #[sea_orm(indexed, default_value = false)]
    pub is_test: bool,
    #[sea_orm(column_type = "Json", nullable)]
    pub variables_json: Option<Json>,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
