//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "order_items")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(indexed)]
    pub order_id: i64,
    #[sea_orm(indexed)]
    pub product_id: i64,
    #[sea_orm(indexed, default_value = 0)]
    pub sku_id: i64,
    #[sea_orm(column_type = "Json", nullable)]
    pub title_json: Option<Json>,
    #[sea_orm(column_type = "Json", nullable)]
    pub sku_snapshot_json: Option<Json>,
    #[sea_orm(column_type = "Json", nullable)]
    pub tags: Option<Json>,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub original_unit_price: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub unit_price: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub cost_price: Decimal,
    pub quantity: i32,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub original_total_price: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub total_price: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub coupon_discount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub member_discount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub promotion_discount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub wholesale_discount: Decimal,
    #[sea_orm(indexed, nullable)]
    pub promotion_id: Option<i64>,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub fulfillment_type: String,
    #[sea_orm(column_type = "Json", nullable)]
    pub manual_form_schema_snapshot_json: Option<Json>,
    #[sea_orm(column_type = "Json", nullable)]
    pub manual_form_submission_json: Option<Json>,
    #[sea_orm(column_type = "Json", nullable)]
    pub instructions_json: Option<Json>,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
