//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "order_refund_records")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(indexed, default_value = 0)]
    pub user_id: i64,
    #[sea_orm(column_type = "String(StringLen::N(255))", indexed)]
    pub guest_email: String,
    #[sea_orm(indexed)]
    pub order_id: i64,
    #[sea_orm(
        column_type = "String(StringLen::N(32))",
        indexed,
        column_name = "type"
    )]
    pub type_: String,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub amount: Decimal,
    #[sea_orm(default_value = false)]
    pub payment_fee_refunded: bool,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub payment_fee_refunded_amount: Decimal,
    #[sea_orm(column_type = "String(StringLen::N(16))")]
    pub currency: String,
    #[sea_orm(column_type = "Text")]
    pub remark: String,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
