//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "orders")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "String(StringLen::N(255))", unique)]
    pub order_no: String,
    #[sea_orm(indexed, nullable)]
    pub parent_id: Option<i64>,
    #[sea_orm(indexed)]
    pub user_id: i64,
    #[sea_orm(column_type = "String(StringLen::N(255))", indexed)]
    pub guest_email: String,
    #[sea_orm(column_type = "String(StringLen::N(200))")]
    pub guest_password: String,
    #[sea_orm(column_type = "String(StringLen::N(20))")]
    pub guest_locale: String,
    #[sea_orm(column_type = "String(StringLen::N(255))", indexed)]
    pub status: String,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub currency: String,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub original_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub discount_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub member_discount_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub promotion_discount_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub wholesale_discount_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub total_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub wallet_paid_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub online_paid_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub refunded_amount: Decimal,
    #[sea_orm(indexed, nullable)]
    pub member_level_id: Option<i64>,
    #[sea_orm(indexed, nullable)]
    pub coupon_id: Option<i64>,
    #[sea_orm(indexed, nullable)]
    pub promotion_id: Option<i64>,
    #[sea_orm(indexed, nullable)]
    pub affiliate_profile_id: Option<i64>,
    #[sea_orm(column_type = "String(StringLen::N(32))", indexed)]
    pub affiliate_code: String,
    #[sea_orm(indexed, nullable)]
    pub reseller_id: Option<i64>,
    #[sea_orm(column_type = "String(StringLen::N(255))", indexed)]
    pub reseller_domain: String,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub reseller_profit_amount: Decimal,
    #[sea_orm(column_type = "String(StringLen::N(64))")]
    pub client_ip: String,
    #[sea_orm(column_type = "String(StringLen::N(80))", indexed)]
    pub risk_ip: String,
    #[sea_orm(indexed, nullable)]
    pub expires_at: Option<DateTimeUtc>,
    #[sea_orm(indexed, nullable)]
    pub paid_at: Option<DateTimeUtc>,
    #[sea_orm(indexed, nullable)]
    pub canceled_at: Option<DateTimeUtc>,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
