//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "payment_channels")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub name: String,
    #[sea_orm(column_type = "String(StringLen::N(512))")]
    pub icon: String,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub provider_type: String,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub channel_type: String,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub interaction_mode: String,
    #[sea_orm(column_type = "Decimal(Some((6, 2)))")]
    pub fee_rate: Decimal,
    #[sea_orm(column_type = "Decimal(Some((6, 2)))")]
    pub fixed_fee: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub min_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub max_amount: Decimal,
    #[sea_orm(default_value = false)]
    pub hide_amount_out_range: bool,
    #[sea_orm(column_type = "Json", nullable)]
    pub payment_roles: Option<Json>,
    #[sea_orm(column_type = "Json", nullable)]
    pub member_levels: Option<Json>,
    #[sea_orm(column_type = "Json", nullable)]
    pub payment_types: Option<Json>,
    #[sea_orm(column_type = "Json", nullable)]
    pub config_json: Option<Json>,
    #[sea_orm(indexed, default_value = true)]
    pub is_active: bool,
    #[sea_orm(default_value = 0)]
    pub sort_order: i32,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
