//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "payments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(indexed)]
    pub order_id: i64,
    #[sea_orm(indexed)]
    pub channel_id: i64,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub provider_type: String,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub channel_type: String,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub interaction_mode: String,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((6, 2)))")]
    pub fee_rate: Decimal,
    #[sea_orm(column_type = "Decimal(Some((6, 2)))")]
    pub fixed_fee: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub fee_amount: Decimal,
    #[sea_orm(
        column_type = "String(StringLen::N(32))",
        indexed,
        default_value = "none"
    )]
    pub fee_policy: String,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub currency: String,
    #[sea_orm(column_type = "String(StringLen::N(255))", indexed)]
    pub status: String,
    #[sea_orm(column_type = "String(StringLen::N(64))", indexed)]
    pub exception_code: String,
    #[sea_orm(column_type = "String(StringLen::N(255))", indexed)]
    pub provider_ref: String,
    #[sea_orm(column_type = "String(StringLen::N(64))", indexed)]
    pub gateway_order_no: String,
    #[sea_orm(column_type = "Json", nullable)]
    pub provider_payload: Option<Json>,
    #[sea_orm(column_type = "Text")]
    pub pay_url: String,
    #[sea_orm(column_type = "Text")]
    pub qr_code: String,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub paid_at: Option<DateTimeUtc>,
    #[sea_orm(indexed, nullable)]
    pub expired_at: Option<DateTimeUtc>,
    #[sea_orm(indexed, nullable)]
    pub superseded_at: Option<DateTimeUtc>,
    #[sea_orm(indexed, nullable)]
    pub superseded_by_payment_id: Option<i64>,
    #[sea_orm(indexed, nullable)]
    pub callback_at: Option<DateTimeUtc>,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
