//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "posts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "String(StringLen::N(255))", unique)]
    pub slug: String,
    #[sea_orm(
        column_type = "String(StringLen::N(255))",
        indexed,
        column_name = "type"
    )]
    pub type_: String,
    #[sea_orm(column_type = "Json", nullable)]
    pub title_json: Option<Json>,
    #[sea_orm(column_type = "Json", nullable)]
    pub summary_json: Option<Json>,
    #[sea_orm(column_type = "Json", nullable)]
    pub content_json: Option<Json>,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub thumbnail: String,
    #[sea_orm(indexed, nullable)]
    pub category_id: Option<i64>,
    #[sea_orm(indexed, default_value = false)]
    pub is_published: bool,
    #[sea_orm(indexed, nullable)]
    pub published_at: Option<DateTimeUtc>,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
