//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "post_categories")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(indexed, nullable)]
    pub parent_id: Option<i64>,
    #[sea_orm(column_type = "String(StringLen::N(255))", unique)]
    pub slug: String,
    #[sea_orm(column_type = "Json", nullable)]
    pub name_json: Option<Json>,
    #[sea_orm(column_type = "String(StringLen::N(500))")]
    pub icon: String,
    #[sea_orm(indexed, default_value = true)]
    pub is_active: bool,
    #[sea_orm(indexed, default_value = 0)]
    pub sort_order: i32,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
