//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "procurement_orders")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(indexed)]
    pub connection_id: i64,
    #[sea_orm(indexed)]
    pub local_order_id: i64,
    #[sea_orm(column_type = "String(StringLen::N(64))", indexed)]
    pub local_order_no: String,
    pub upstream_order_id: i64,
    #[sea_orm(column_type = "String(StringLen::N(64))", indexed)]
    pub upstream_order_no: String,
    #[sea_orm(
        column_type = "String(StringLen::N(20))",
        indexed,
        default_value = "pending"
    )]
    pub status: String,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub upstream_amount: Decimal,
    #[sea_orm(column_type = "String(StringLen::N(10))")]
    pub upstream_currency: String,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub local_sell_amount: Decimal,
    #[sea_orm(column_type = "String(StringLen::N(10))")]
    pub currency: String,
    #[sea_orm(column_type = "Text")]
    pub error_message: String,
    #[sea_orm(default_value = 0)]
    pub retry_count: i32,
    #[sea_orm(indexed, nullable)]
    pub next_retry_at: Option<DateTimeUtc>,
    #[sea_orm(column_type = "Text")]
    pub upstream_payload: String,
    #[sea_orm(column_type = "String(StringLen::N(64))", indexed)]
    pub trace_id: String,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
