//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "products")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(indexed)]
    pub category_id: i64,
    #[sea_orm(column_type = "String(StringLen::N(255))", unique)]
    pub slug: String,
    #[sea_orm(column_type = "Json", nullable)]
    pub seo_meta_json: Option<Json>,
    #[sea_orm(column_type = "Json", nullable)]
    pub title_json: Option<Json>,
    #[sea_orm(column_type = "Json", nullable)]
    pub description_json: Option<Json>,
    #[sea_orm(column_type = "Json", nullable)]
    pub content_json: Option<Json>,
    #[sea_orm(column_type = "Json", nullable)]
    pub instructions_json: Option<Json>,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub price_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub cost_price_amount: Decimal,
    #[sea_orm(column_type = "Json", nullable)]
    pub wholesale_prices: Option<Json>,
    #[sea_orm(column_type = "Json", nullable)]
    pub images: Option<Json>,
    #[sea_orm(column_type = "Json", nullable)]
    pub tags: Option<Json>,
    #[sea_orm(column_type = "String(StringLen::N(20))", default_value = "member")]
    pub purchase_type: String,
    #[sea_orm(default_value = 0)]
    pub min_purchase_quantity: i32,
    #[sea_orm(default_value = 0)]
    pub max_purchase_quantity: i32,
    #[sea_orm(column_type = "String(StringLen::N(20))", default_value = "exact")]
    pub stock_display_mode: String,
    #[sea_orm(column_type = "String(StringLen::N(20))", default_value = "manual")]
    pub fulfillment_type: String,
    #[sea_orm(column_type = "Json", nullable)]
    pub manual_form_schema_json: Option<Json>,
    #[sea_orm(default_value = 0)]
    pub manual_stock_total: i32,
    #[sea_orm(default_value = 0)]
    pub manual_stock_locked: i32,
    #[sea_orm(default_value = 0)]
    pub manual_stock_sold: i32,
    #[sea_orm(column_type = "Text")]
    pub payment_channel_ids: String,
    #[sea_orm(indexed, default_value = false)]
    pub is_affiliate_enabled: bool,
    #[sea_orm(indexed, default_value = false)]
    pub is_mapped: bool,
    #[sea_orm(indexed, default_value = false)]
    pub is_active: bool,
    #[sea_orm(indexed, default_value = 0)]
    pub sort_order: i32,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
