//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "product_mappings")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(indexed)]
    pub connection_id: i64,
    #[sea_orm(unique)]
    pub local_product_id: i64,
    pub upstream_product_id: i64,
    #[sea_orm(column_type = "String(StringLen::N(20))", default_value = "manual")]
    pub upstream_fulfillment_type: String,
    #[sea_orm(
        column_type = "String(StringLen::N(16))",
        indexed,
        default_value = "active"
    )]
    pub upstream_status: String,
    #[sea_orm(default_value = true)]
    pub is_active: bool,
    #[sea_orm(nullable)]
    pub last_synced_at: Option<DateTimeUtc>,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
