//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "promotions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub name: String,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub scope_type: String,
    #[sea_orm(indexed)]
    pub scope_ref_id: i64,
    #[sea_orm(column_type = "String(StringLen::N(255))", column_name = "type")]
    pub type_: String,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub value: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub min_amount: Decimal,
    #[sea_orm(indexed, nullable)]
    pub starts_at: Option<DateTimeUtc>,
    #[sea_orm(indexed, nullable)]
    pub ends_at: Option<DateTimeUtc>,
    #[sea_orm(default_value = true)]
    pub is_active: bool,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
