//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "reconciliation_items")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(indexed)]
    pub job_id: i64,
    #[sea_orm(indexed)]
    pub procurement_order_id: i64,
    #[sea_orm(column_type = "String(StringLen::N(64))")]
    pub local_order_no: String,
    #[sea_orm(column_type = "String(StringLen::N(64))")]
    pub upstream_order_no: String,
    #[sea_orm(column_type = "String(StringLen::N(20))")]
    pub local_status: String,
    #[sea_orm(column_type = "String(StringLen::N(20))")]
    pub upstream_status: String,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub local_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub upstream_amount: Decimal,
    #[sea_orm(column_type = "String(StringLen::N(40))")]
    pub mismatch_type: String,
    #[sea_orm(default_value = false)]
    pub resolved: bool,
    #[sea_orm(nullable)]
    pub resolved_by: Option<i64>,
    #[sea_orm(nullable)]
    pub resolved_at: Option<DateTimeUtc>,
    #[sea_orm(column_type = "Text")]
    pub remark: String,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
