//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "reconciliation_jobs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(indexed)]
    pub connection_id: i64,
    #[sea_orm(column_type = "String(StringLen::N(20))", column_name = "type")]
    pub type_: String,
    #[sea_orm(column_type = "String(StringLen::N(20))", default_value = "pending")]
    pub status: String,
    pub time_range_start: DateTimeUtc,
    pub time_range_end: DateTimeUtc,
    #[sea_orm(default_value = 0)]
    pub total_count: i32,
    #[sea_orm(default_value = 0)]
    pub matched_count: i32,
    #[sea_orm(default_value = 0)]
    pub mismatched_count: i32,
    #[sea_orm(column_type = "Text")]
    pub result_json: String,
    #[sea_orm(nullable)]
    pub started_at: Option<DateTimeUtc>,
    #[sea_orm(nullable)]
    pub finished_at: Option<DateTimeUtc>,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
