//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "reseller_order_snapshots")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub order_id: i64,
    #[sea_orm(indexed)]
    pub reseller_id: i64,
    #[sea_orm(column_type = "String(StringLen::N(255))", indexed)]
    pub domain: String,
    #[sea_orm(column_type = "String(StringLen::N(16))")]
    pub currency: String,
    #[sea_orm(indexed)]
    pub reseller_user_id: i64,
    #[sea_orm(indexed, default_value = 0)]
    pub buyer_user_id: i64,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub base_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub reseller_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub profit_amount: Decimal,
    #[sea_orm(indexed, default_value = true)]
    pub profit_eligible: bool,
    #[sea_orm(column_type = "String(StringLen::N(64))", indexed)]
    pub profit_block_reason: String,
    #[sea_orm(column_type = "Json", nullable)]
    pub pricing_snapshot_json: Option<Json>,
    #[sea_orm(column_type = "Json", nullable)]
    pub risk_snapshot_json: Option<Json>,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
