//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "reseller_product_settings")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "idx_reseller_product_setting_scope", indexed)]
    pub reseller_id: i64,
    #[sea_orm(unique_key = "idx_reseller_product_setting_scope", indexed)]
    pub product_id: i64,
    #[sea_orm(
        unique_key = "idx_reseller_product_setting_scope",
        indexed,
        default_value = 0
    )]
    pub sku_id: i64,
    #[sea_orm(default_value = true)]
    pub is_listed: bool,
    #[sea_orm(column_type = "String(StringLen::N(32))", default_value = "inherit")]
    pub pricing_mode: String,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub markup_percent: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub fixed_markup_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub fixed_price_amount: Decimal,
    #[sea_orm(indexed, default_value = 0)]
    pub sort_order: i32,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
