//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "reseller_balance_accounts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(indexed)]
    pub reseller_id: i64,
    #[sea_orm(column_type = "String(StringLen::N(16))", indexed)]
    pub currency: String,
    #[sea_orm(
        column_type = "String(StringLen::N(32))",
        indexed,
        default_value = "normal"
    )]
    pub status: String,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub available_amount_cache: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub locked_amount_cache: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub negative_amount_cache: Decimal,
    #[sea_orm(default_value = 0)]
    pub last_ledger_entry_id: i64,
    #[sea_orm(column_type = "Text")]
    pub risk_note: String,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
