//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "reseller_site_configs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(indexed)]
    pub reseller_id: i64,
    #[sea_orm(column_type = "String(StringLen::N(120))")]
    pub site_name: String,
    #[sea_orm(column_type = "String(StringLen::N(500))")]
    pub logo: String,
    #[sea_orm(column_type = "String(StringLen::N(500))")]
    pub favicon: String,
    #[sea_orm(column_type = "Json", nullable)]
    pub announcement_json: Option<Json>,
    #[sea_orm(column_type = "Json", nullable)]
    pub support_json: Option<Json>,
    #[sea_orm(column_type = "Json", nullable)]
    pub seo_json: Option<Json>,
    #[sea_orm(column_type = "Json", nullable)]
    pub footer_links_json: Option<Json>,
    #[sea_orm(column_type = "Json", nullable)]
    pub nav_config_json: Option<Json>,
    #[sea_orm(column_type = "Json", nullable)]
    pub theme_json: Option<Json>,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
