//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "reseller_related_accounts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(indexed)]
    pub reseller_id: i64,
    #[sea_orm(indexed)]
    pub user_id: i64,
    #[sea_orm(column_type = "String(StringLen::N(32))", indexed)]
    pub relation_type: String,
    #[sea_orm(column_type = "String(StringLen::N(64))")]
    pub source: String,
    #[sea_orm(
        column_type = "String(StringLen::N(32))",
        indexed,
        default_value = "active"
    )]
    pub status: String,
    #[sea_orm(column_type = "Text")]
    pub remark: String,
    #[sea_orm(indexed, nullable)]
    pub created_by: Option<i64>,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
