//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "reseller_profiles")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub user_id: i64,
    #[sea_orm(
        column_type = "String(StringLen::N(32))",
        indexed,
        default_value = "pending_review"
    )]
    pub status: String,
    #[sea_orm(column_type = "Text")]
    pub apply_reason: String,
    #[sea_orm(column_type = "Text")]
    pub reject_reason: String,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub default_markup_percent: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub max_markup_percent: Decimal,
    #[sea_orm(
        column_type = "String(StringLen::N(32))",
        indexed,
        default_value = "normal"
    )]
    pub settlement_status: String,
    #[sea_orm(indexed, nullable)]
    pub reviewed_by: Option<i64>,
    #[sea_orm(indexed, nullable)]
    pub reviewed_at: Option<DateTimeUtc>,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
