//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "reseller_ledger_entries")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(indexed)]
    pub reseller_id: i64,
    #[sea_orm(indexed, nullable)]
    pub order_id: Option<i64>,
    #[sea_orm(
        column_type = "String(StringLen::N(32))",
        indexed,
        column_name = "type"
    )]
    pub type_: String,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub amount: Decimal,
    #[sea_orm(column_type = "String(StringLen::N(16))", indexed)]
    pub currency: String,
    #[sea_orm(column_type = "String(StringLen::N(160))", unique)]
    pub idempotency_key: String,
    #[sea_orm(column_type = "Json", nullable)]
    pub metadata_json: Option<Json>,
    #[sea_orm(column_type = "String(StringLen::N(32))", indexed)]
    pub status: String,
    #[sea_orm(indexed, nullable)]
    pub available_at: Option<DateTimeUtc>,
    #[sea_orm(indexed, nullable)]
    pub withdraw_request_id: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub remark: String,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
