//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "reseller_domains")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(indexed)]
    pub reseller_id: i64,
    #[sea_orm(column_type = "String(StringLen::N(255))", indexed)]
    pub domain: String,
    #[sea_orm(column_type = "String(StringLen::N(24))", column_name = "type")]
    pub type_: String,
    #[sea_orm(column_type = "String(StringLen::N(128))")]
    pub verification_token: String,
    #[sea_orm(
        column_type = "String(StringLen::N(24))",
        indexed,
        default_value = "pending"
    )]
    pub verification_status: String,
    #[sea_orm(
        column_type = "String(StringLen::N(24))",
        indexed,
        default_value = "pending_review"
    )]
    pub status: String,
    #[sea_orm(default_value = false)]
    pub is_primary: bool,
    #[sea_orm(indexed, nullable)]
    pub verified_at: Option<DateTimeUtc>,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
