//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "site_connections")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "String(StringLen::N(100))")]
    pub name: String,
    #[sea_orm(column_type = "String(StringLen::N(500))")]
    pub base_url: String,
    #[sea_orm(column_type = "String(StringLen::N(64))")]
    pub api_key: String,
    #[sea_orm(column_type = "String(StringLen::N(512))")]
    pub api_secret: String,
    #[sea_orm(
        column_type = "String(StringLen::N(20))",
        default_value = "dujiao-next"
    )]
    pub protocol: String,
    #[sea_orm(column_type = "String(StringLen::N(500))")]
    pub callback_url: String,
    #[sea_orm(column_type = "String(StringLen::N(20))", default_value = "pending")]
    pub status: String,
    #[sea_orm(nullable)]
    pub last_ping_at: Option<DateTimeUtc>,
    #[sea_orm(default_value = false)]
    pub last_ping_ok: bool,
    #[sea_orm(default_value = 5)]
    pub retry_max: i32,
    #[sea_orm(
        column_type = "String(StringLen::N(200))",
        default_value = "[30,60,300]"
    )]
    pub retry_intervals: String,
    #[sea_orm(column_type = "Decimal(Some((16, 6)))")]
    pub exchange_rate: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 4)))")]
    pub price_markup_percent: Decimal,
    #[sea_orm(column_type = "String(StringLen::N(20))", default_value = "none")]
    pub price_rounding_mode: String,
    #[sea_orm(default_value = false)]
    pub auto_sync_price: bool,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
