//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "sku_mappings")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(indexed)]
    pub product_mapping_id: i64,
    #[sea_orm(indexed)]
    pub local_sku_id: i64,
    pub upstream_sku_id: i64,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub upstream_price: Decimal,
    #[sea_orm(default_value = 0)]
    pub upstream_stock: i32,
    #[sea_orm(default_value = true)]
    pub upstream_is_active: bool,
    #[sea_orm(nullable)]
    pub stock_synced_at: Option<DateTimeUtc>,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
