//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "telegram_broadcasts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "String(StringLen::N(200))")]
    pub title: String,
    #[sea_orm(column_type = "String(StringLen::N(32))", indexed)]
    pub recipient_type: String,
    #[sea_orm(column_type = "Json", nullable)]
    pub filters_json: Option<Json>,
    #[sea_orm(column_type = "Json", nullable)]
    pub recipient_chat_ids: Option<Json>,
    #[sea_orm(default_value = 0)]
    pub recipient_count: i32,
    #[sea_orm(default_value = 0)]
    pub success_count: i32,
    #[sea_orm(default_value = 0)]
    pub failed_count: i32,
    #[sea_orm(
        column_type = "String(StringLen::N(32))",
        indexed,
        default_value = "pending"
    )]
    pub status: String,
    #[sea_orm(column_type = "Text")]
    pub message_html: String,
    #[sea_orm(column_type = "String(StringLen::N(500))")]
    pub attachment_url: String,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub attachment_name: String,
    #[sea_orm(nullable)]
    pub started_at: Option<DateTimeUtc>,
    #[sea_orm(nullable)]
    pub completed_at: Option<DateTimeUtc>,
    #[sea_orm(column_type = "Text")]
    pub last_error: String,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
