//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "user_oauth_identities")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(indexed)]
    pub user_id: i64,
    #[sea_orm(
        column_type = "String(StringLen::N(32))",
        unique_key = "idx_provider_user"
    )]
    pub provider: String,
    #[sea_orm(
        column_type = "String(StringLen::N(255))",
        unique_key = "idx_provider_user"
    )]
    pub provider_user_id: String,
    #[sea_orm(column_type = "String(StringLen::N(128))")]
    pub username: String,
    #[sea_orm(column_type = "Text")]
    pub avatar_url: String,
    #[sea_orm(nullable)]
    pub auth_at: Option<DateTimeUtc>,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
