//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "String(StringLen::N(255))", unique)]
    pub email: String,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub password_hash: String,
    #[sea_orm(default_value = false)]
    pub password_setup_required: bool,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub display_name: String,
    #[sea_orm(column_type = "String(StringLen::N(255))", default_value = "zh-CN")]
    pub locale: String,
    #[sea_orm(column_type = "String(StringLen::N(255))", default_value = "active")]
    pub status: String,
    #[sea_orm(default_value = 0)]
    pub member_level_id: i64,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub total_recharged: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub total_spent: Decimal,
    #[sea_orm(column_type = "Text")]
    pub admin_note: String,
    #[sea_orm(default_value = 0)]
    pub token_version: i64,
    #[sea_orm(indexed, nullable)]
    pub token_invalid_before: Option<DateTimeUtc>,
    #[sea_orm(column_type = "String(StringLen::N(512))")]
    pub totp_secret: String,
    #[sea_orm(indexed, nullable)]
    pub totp_enabled_at: Option<DateTimeUtc>,
    #[sea_orm(column_type = "String(StringLen::N(512))")]
    pub totp_pending_secret: String,
    #[sea_orm(nullable)]
    pub totp_pending_expires_at: Option<DateTimeUtc>,
    #[sea_orm(column_type = "Text")]
    pub recovery_codes: String,
    #[sea_orm(nullable)]
    pub email_verified_at: Option<DateTimeUtc>,
    #[sea_orm(nullable)]
    pub last_login_at: Option<DateTimeUtc>,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
