//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "wallet_transactions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(indexed)]
    pub user_id: i64,
    #[sea_orm(indexed, nullable)]
    pub operator_admin_id: Option<i64>,
    #[sea_orm(indexed, nullable)]
    pub order_id: Option<i64>,
    #[sea_orm(
        column_type = "String(StringLen::N(40))",
        indexed,
        column_name = "type"
    )]
    pub type_: String,
    #[sea_orm(column_type = "String(StringLen::N(16))", indexed)]
    pub direction: String,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub balance_before: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub balance_after: Decimal,
    #[sea_orm(column_type = "String(StringLen::N(16))", default_value = "CNY")]
    pub currency: String,
    #[sea_orm(column_type = "String(StringLen::N(120))", unique)]
    pub reference: String,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub remark: String,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
