//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "wallet_recharge_orders")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "String(StringLen::N(40))", unique)]
    pub recharge_no: String,
    #[sea_orm(indexed)]
    pub user_id: i64,
    #[sea_orm(unique)]
    pub payment_id: i64,
    #[sea_orm(indexed)]
    pub channel_id: i64,
    #[sea_orm(column_type = "String(StringLen::N(32))")]
    pub provider_type: String,
    #[sea_orm(column_type = "String(StringLen::N(32))")]
    pub channel_type: String,
    #[sea_orm(column_type = "String(StringLen::N(32))")]
    pub interaction_mode: String,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub payable_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((6, 2)))")]
    pub fee_rate: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 2)))")]
    pub fee_amount: Decimal,
    #[sea_orm(column_type = "String(StringLen::N(16))", default_value = "CNY")]
    pub currency: String,
    #[sea_orm(column_type = "String(StringLen::N(20))", indexed)]
    pub status: String,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub remark: String,
    #[sea_orm(indexed, nullable)]
    pub paid_at: Option<DateTimeUtc>,
    #[sea_orm(indexed)]
    pub created_at: DateTimeUtc,
    #[sea_orm(indexed)]
    pub updated_at: DateTimeUtc,
    #[sea_orm(indexed, nullable)]
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
