#!/usr/bin/env python3
"""Generate sea-orm entities from the original project's GORM schema dump.

Input : docs/reference/schema.json (exported with gorm/schema.Parse)
Output: crates/infra/src/db/entity/<table>.rs and mod.rs

Re-run after editing the mapping rules; generated files carry a header and must
not be edited by hand (add extra entities in crates/infra/src/db/entity/extra/).
"""
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[2]
SCHEMA = json.loads((ROOT / "docs/reference/schema.json").read_text())
OUT = ROOT / "backend/crates/infra/src/db/entity"
RUST_KEYWORDS = {"type", "ref", "match", "mod", "use", "where", "fn", "struct", "enum", "move", "self", "loop", "box", "final"}
HEADER = "//! Generated by `scripts/gen_entities.py` from the original GORM schema. Do not edit.\n"


def rust_type(f):
    go, dt = f["GoType"], f["DataType"]
    ptr = go.startswith("*")
    base = go.lstrip("*")
    attrs = []
    if base in ("uint", "uint64", "int64"):
        ty = "i64"
    elif base == "int":
        ty = "i32"
    elif base == "bool":
        ty = "bool"
    elif base == "time.Time":
        ty = "DateTimeUtc"
    elif base in ("money.Amount", "decimal.Decimal"):
        m = re.match(r"decimal\((\d+),(\d+)\)", dt)
        p, s = (m.group(1), m.group(2)) if m else ("20", "2")
        attrs.append(f'column_type = "Decimal(Some(({p}, {s})))"')
        ty = "Decimal"
    elif dt == "json":
        attrs.append('column_type = "Json"')
        ty = "Json"
        ptr = True  # GORM writes NULL for nil maps/slices
    elif base == "string":
        if dt == "text":
            attrs.append('column_type = "Text"')
        else:
            m = re.match(r"varchar\((\d+)\)", dt)
            size = int(m.group(1)) if m else (f["Size"] or 255)
            attrs.append(f'column_type = "String(StringLen::N({size}))"')
        ty = "String"
    else:
        raise SystemExit(f"unmapped type {go} {dt} in {f['DBName']}")
    return ty, ptr, attrs


def default_attr(f, ty):
    if not f["HasDefault"] or f["Primary"]:
        return None
    d = f["Default"]
    if d is None or d == "":
        return None
    d = d.strip("'")
    if ty == "bool":
        return f"default_value = {str(d.lower() in ('true', '1')).lower()}"
    if ty in ("i32", "i64"):
        return f"default_value = {int(d)}" if re.fullmatch(r"-?\d+", d) else None
    if ty == "Decimal":
        return None
    if ty == "String":
        return f'default_value = "{d}"'
    return None


def gen_table(t):
    table = t["Table"]
    indexes = t["Indexes"] or []
    unique_single = {i["Fields"][0] for i in indexes if i["Unique"] and len(i["Fields"]) == 1}
    composite_unique = {}
    for i in indexes:
        if i["Unique"] and len(i["Fields"]) > 1:
            for col in i["Fields"]:
                composite_unique[col] = i["Name"]
    indexed = {i["Fields"][0] for i in indexes if not i["Unique"] and len(i["Fields"]) == 1}

    lines = [HEADER, "use sea_orm::entity::prelude::*;\n", "",
             "#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]",
             f'#[sea_orm(table_name = "{table}")]', "pub struct Model {"]
    for f in t["Fields"]:
        col = f["DBName"]
        ty, nullable, attrs = rust_type(f)
        if f["Primary"]:
            if ty == "String":
                attrs.insert(0, "primary_key, auto_increment = false")
            else:
                attrs.insert(0, "primary_key")
                ty = "i64"
        else:
            if col in unique_single:
                attrs.append("unique")
            if col in composite_unique:
                attrs.append(f'unique_key = "{composite_unique[col]}"')
            if col in indexed:
                attrs.append("indexed")
            if nullable:
                attrs.append("nullable")
            d = default_attr(f, ty)
            if d:
                attrs.append(d)
        name = col
        if col in RUST_KEYWORDS:
            name = f"{col}_"
            attrs.append(f'column_name = "{col}"')
        if attrs:
            lines.append(f"    #[sea_orm({', '.join(attrs)})]")
        field_ty = f"Option<{ty}>" if nullable and not f["Primary"] else ty
        lines.append(f"    pub {name}: {field_ty},")
    lines += ["}", "", "#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]",
              "pub enum Relation {}", "", "impl ActiveModelBehavior for ActiveModel {}", ""]
    return "\n".join(lines)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    mods = []
    for t in SCHEMA:
        (OUT / f"{t['Table']}.rs").write_text(gen_table(t))
        mods.append(t["Table"])
    mod_rs = [HEADER.replace("//!", "//!", 1), "//! One module per table of the original schema.\n"]
    mod_rs += [f"pub mod {m};" for m in sorted(mods)]
    mod_rs += ["", "pub mod extra;", "pub use extra::*;", ""]
    (OUT / "mod.rs").write_text("\n".join(mod_rs))
    print(f"generated {len(mods)} entities")


if __name__ == "__main__":
    main()
