import fs from 'node:fs'
const U = JSON.parse(fs.readFileSync(new URL('./qa-user.json', import.meta.url)))
const ulogin = async (page, email, password) => page.evaluate(async ({ email, password }) => (await (await fetch('/api/v1/auth/login', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email, password }) })).json()), { email, password })
const me = async (page, tok) => page.evaluate(async (tok) => (await (await fetch('/api/v1/me', { headers: { authorization: 'Bearer ' + tok } })).json()), tok)
export default async ({ page, api, shot, log, admin }) => {
  const l = await ulogin(page, U.email, U.password); const tok = l.data?.token; log('user login', l.status_code)
  log('me before', JSON.stringify(await me(page, tok)).slice(0, 120))
  await page.goto(admin + '/users'); await page.waitForLoadState('networkidle')
  await page.getByPlaceholder('用户ID').fill(String(U.id)); await page.waitForTimeout(1200)
  await page.getByRole('button', { name: '编辑' }).first().click(); await page.waitForTimeout(600)
  const dlg = page.locator('[role=dialog]').last()
  await shot(page, 'd-user-edit-dialog', false)
  // validation: clear email & nickname
  const inputs = dlg.locator('input')
  await inputs.nth(0).fill(''); await inputs.nth(1).fill('')
  await dlg.getByRole('button', { name: /保存|确认/ }).last().click(); await page.waitForTimeout(700)
  log('validation', (await dlg.innerText()).match(/请[^\n]*|不能[^\n]*|格式[^\n]*/g)?.join(' / '))
  await shot(page, 'd-user-edit-validation', false)
  await inputs.nth(0).fill('bad-email'); await inputs.nth(1).fill('QA Nick')
  await dlg.getByRole('button', { name: /保存|确认/ }).last().click(); await page.waitForTimeout(900)
  log('bad email', (await dlg.innerText().catch(() => 'closed')).match(/请[^\n]*|邮箱[^\n]*/g)?.join(' / '))
  await inputs.nth(0).fill(U.email); await inputs.nth(1).fill('QA Nick 编辑')
  await inputs.nth(2).fill('NewPass12345!')
  await dlg.locator('textarea').fill('qa admin note')
  const sels = dlg.locator('select'); log('selects', await sels.count())
  for (let i = 0; i < await sels.count(); i++) log('select', i, (await sels.nth(i).locator('option').allInnerTexts()).join('/'))
  await sels.nth(0).selectOption({ label: 'English' }).catch(e => log('locale sel fail', e.message.slice(0, 60)))
  const [res] = await Promise.all([page.waitForResponse(r => r.request().method() === 'PUT' && r.url().includes('/admin/users/'), { timeout: 8000 }).catch(() => null), dlg.getByRole('button', { name: /保存|确认/ }).last().click()])
  log('PUT', res ? JSON.stringify(res.request().postDataJSON()) : 'none', res ? (await res.text()).slice(0, 200) : '')
  await page.waitForTimeout(1000); await shot(page, 'd-user-after-edit')
  log('me after pw reset (old token)', JSON.stringify(await me(page, tok)).slice(0, 150))
  const l2 = await ulogin(page, U.email, 'NewPass12345!'); log('login new pw', l2.status_code)
  const l3 = await ulogin(page, U.email, U.password); log('login old pw', l3.status_code, l3.msg)
  const u = await api('GET', '/admin/users/' + U.id); log('user now', JSON.stringify(u.data).slice(0, 400))
}
