import fs from 'node:fs'
const U = JSON.parse(fs.readFileSync(new URL('./qa-user.json', import.meta.url)))
const utoken = async (page) => page.evaluate(async (U) => (await (await fetch('/api/v1/auth/login', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email: U.email, password: U.password }) })).json()).data.token, U)
const preview = async (page, tok) => page.evaluate(async (tok) => (await (await fetch('/api/v1/orders/preview', { method: 'POST', headers: { 'content-type': 'application/json', authorization: 'Bearer ' + tok }, body: JSON.stringify({ items: [{ product_id: 8, sku_id: 12, quantity: 1 }] }) })).json()), tok)
const txt = async (page) => (await page.locator('[role=status],[role=alert],[class*=notice],[class*=toast]').allInnerTexts().catch(() => [])).join(' | ').slice(0, 200)
export default async ({ page, api, shot, log, admin }) => {
  await page.goto(admin + '/member-levels'); await page.waitForLoadState('networkidle')
  const [bf] = await Promise.all([page.waitForResponse(r => r.url().includes('/backfill'), { timeout: 8000 }).catch(() => null), page.getByRole('button', { name: /批量分配默认等级/ }).click()])
  await page.waitForTimeout(400)
  const c = page.locator('[role=dialog] button', { hasText: /确认|确定/ }).last(); if (await c.isVisible().catch(() => false)) { log('backfill has confirm dialog'); const [r2] = await Promise.all([page.waitForResponse(r => r.url().includes('/backfill'), { timeout: 8000 }).catch(() => null), c.click()]); log('backfill resp', r2 ? await r2.text() : 'none') } else log('backfill resp', bf ? await bf.text() : 'none')
  await page.waitForTimeout(800); log('toast', await txt(page)); await shot(page, 'd-levels-backfill-no-default', false)
  await page.getByRole('button', { name: /创建等级/ }).click(); await page.waitForTimeout(500)
  const dlg = page.locator('[role=dialog]').last()
  await dlg.getByRole('button', { name: /保存/ }).click(); await page.waitForTimeout(700)
  log('empty save', (await dlg.innerText()).match(/此项为必填|请[^\n]*|不能[^\n]*/g)?.join(' / '), '| toast', await txt(page))
  await shot(page, 'd-levels-create-empty', false)
  for (const code of ['zh-CN', 'zh-TW', 'en-US']) { await dlg.locator(`button[title="${code}"]`).first().click(); await dlg.locator('input').first().fill('QA 测试等级 ' + code) }
  const num = dlg.locator('input[type=number]')
  await dlg.locator('input:not([type=number])').nth(1).fill('qa-vip-d')
  await num.nth(0).fill('95'); await num.nth(1).fill('100')
  const [res] = await Promise.all([page.waitForResponse(r => r.request().method() === 'POST' && r.url().includes('/member-levels'), { timeout: 8000 }).catch(() => null), dlg.getByRole('button', { name: /保存/ }).click()])
  log('create', res ? JSON.stringify(res.request().postDataJSON()) : 'none', res ? (await res.text()).slice(0, 300) : '')
  await page.waitForTimeout(1000); await shot(page, 'd-levels-list')
  const lv = (await api('GET', '/admin/member-levels?page=1&page_size=50')).data.find(l => l.slug === 'qa-vip-d')
  log('level', JSON.stringify(lv))
  // assign via user detail dropdown
  const tok = await utoken(page)
  log('price before', JSON.stringify((await preview(page, tok)).data?.total_amount ?? (await preview(page, tok))).slice(0, 200))
  await page.goto(admin + '/users/' + U.id); await page.waitForLoadState('networkidle')
  const sel = page.locator('main select').first()
  log('level options', (await sel.locator('option').allInnerTexts()).join('/'))
  const [r3] = await Promise.all([page.waitForResponse(r => r.url().includes('/member-level'), { timeout: 8000 }).catch(() => null), sel.selectOption({ label: (await sel.locator('option').allInnerTexts()).find(o => o.includes('QA')) })])
  log('set level', r3 ? (await r3.text()).slice(0, 200) : 'none'); await page.waitForTimeout(800); log('toast', await txt(page))
  await shot(page, 'd-user-level-set')
  const pv = await preview(page, tok); log('price after', pv.data?.total_amount, pv.data?.member_discount_amount, JSON.stringify(pv).slice(0, 300))
  fs.writeFileSync(new URL('./level.json', import.meta.url), JSON.stringify(lv))
}
