import { dialog, field, fieldBox, fillLocalized, selectOption, apiResponse, TS, toast } from './common.mjs'
export default async ({ page, api, shot, log, admin, base }) => {
  await page.goto(`${admin}/categories`)
  await page.waitForLoadState('networkidle')
  // validation: empty
  await page.getByRole('button', { name: 'Add category' }).click()
  let dlg = dialog(page, 'Add category')
  await dlg.getByRole('button', { name: 'Save', exact: true }).click()
  await page.waitForTimeout(500)
  log('empty-validate text:', (await dlg.innerText()).replace(/\s+/g, ' ').slice(0, 600))
  await shot(page, 'c-cat-validation')
  await fillLocalized(fieldBox(dlg, 'Name'), `qa-cat ${TS}`)
  await field(dlg, 'Slug').fill(`qa-cat-${TS}`)
  let r = await apiResponse(page, 'POST', /\/admin\/categories$/, () => dlg.getByRole('button', { name: 'Save', exact: true }).click())
  log('create parent', JSON.stringify(r).slice(0, 300))
  await page.waitForTimeout(800)
  // child
  await page.getByRole('button', { name: 'Add category' }).click()
  dlg = dialog(page, 'Add category')
  await fillLocalized(fieldBox(dlg, 'Name'), `qa-cat-child ${TS}`)
  await field(dlg, 'Slug').fill(`qa-cat-child-${TS}`)
  const parentSel = field(dlg, 'Parent category', 'select')
  log('parent options', (await parentSel.locator('option').allTextContents()).join(' / '))
  await selectOption(parentSel, new RegExp(`qa-cat ${TS}`))
  // icon upload via media picker
  await field(dlg, 'Sort weight').fill('5')
  r = await apiResponse(page, 'POST', /\/admin\/categories$/, () => dlg.getByRole('button', { name: 'Save', exact: true }).click())
  log('create child', JSON.stringify(r).slice(0, 300))
  await page.waitForTimeout(800)
  // duplicate slug
  await page.getByRole('button', { name: 'Add category' }).click()
  dlg = dialog(page, 'Add category')
  await fillLocalized(fieldBox(dlg, 'Name'), `qa-dup ${TS}`)
  await field(dlg, 'Slug').fill(`qa-cat-${TS}`)
  r = await apiResponse(page, 'POST', /\/admin\/categories$/, () => dlg.getByRole('button', { name: 'Save', exact: true }).click())
  log('dup slug', JSON.stringify(r).slice(0, 300), 'dialog text', (await dlg.innerText()).replace(/\s+/g, ' ').slice(-200), await toast(page))
  await shot(page, 'c-cat-dup')
  await dlg.getByRole('button', { name: 'Cancel' }).click()
  await shot(page, 'c-cat-list')
  const cats = await api('GET', '/admin/categories')
  const mine = cats.data.filter((c) => String(c.slug).startsWith('qa-cat'))
  log('mine', JSON.stringify(mine.map((c) => ({ id: c.id, slug: c.slug, parent: c.parent_id, active: c.is_active, sort: c.sort_order }))))
  // edit parent: level should be locked because it has child
  const parentRow = page.locator('tr', { hasText: `qa-cat-${TS}` }).filter({ hasNotText: 'child' }).first()
  await parentRow.getByRole('button', { name: 'Edit' }).click()
  dlg = dialog(page, 'Edit category')
  log('parent select disabled?', await field(dlg, 'Parent category', 'select').isDisabled(), (await dlg.innerText()).replace(/\s+/g, ' ').slice(0, 400))
  await shot(page, 'c-cat-edit-parent')
  await dlg.getByRole('button', { name: 'Cancel' }).click()
  // storefront tree
  const pub = await page.evaluate(async () => (await (await fetch('/api/v1/public/categories')).json()))
  const flat = JSON.stringify(pub.data)
  log('public has parent', flat.includes(`qa-cat-${TS}`), 'child', flat.includes(`qa-cat-child-${TS}`))
  // deactivate child via status badge
  const childRow = page.locator('tr', { hasText: `qa-cat-child-${TS}` })
  await childRow.getByRole('button', { name: /Active/ }).first().click()
  await page.waitForTimeout(1000)
  const pub2 = await page.evaluate(async () => (await (await fetch('/api/v1/public/categories')).json()))
  log('after deactivate child public has child', JSON.stringify(pub2.data).includes(`qa-cat-child-${TS}`))
  await shot(page, 'c-cat-deactivated')
}
