import fs from 'node:fs'
import { selectOption, TS } from './common.mjs'
const msg = async (page) => (await page.locator('.bg-danger-soft, .bg-success-soft, [role=status]').allInnerTexts()).join(' | ').slice(0, 300)
export default async ({ page, api, shot, log, admin }) => {
  const P = `qa-product ${TS}`
  await page.goto(`${admin}/card-secrets`)
  await page.waitForLoadState('networkidle')
  const productSelect = page.locator('select').filter({ has: page.locator('option', { hasText: P }) })
  await selectOption(productSelect, new RegExp(P))
  await page.waitForTimeout(1500)
  const skuSel = page.locator('select').filter({ has: page.locator('option', { hasText: `QA-PRO-${TS}` }) }).first()
  await selectOption(skuSel, new RegExp(`QA-PRO-${TS}`))
  await page.waitForTimeout(1500)
  await shot(page, 'c-secrets-pro')
  log('stats text', (await page.locator('main').innerText()).match(/Available[\s\S]{0,120}/)?.[0]?.replace(/\s+/g, ' '))
  // filter by secret keyword
  await page.getByPlaceholder('Search secret content').fill('php')
  await page.getByRole('button', { name: 'Search', exact: true }).click()
  await page.waitForTimeout(1200)
  const rows = page.locator('tbody tr')
  log('rows after secret filter', await rows.count(), (await rows.allInnerTexts()).join(' || ').replace(/\s+/g, ' ').slice(0, 300))
  // select php row, set status used
  await rows.first().getByRole('checkbox').click()
  const statusTarget = page.locator('select').filter({ has: page.locator('option', { hasText: 'Used' }) }).last()
  await selectOption(statusTarget, /Used/)
  await page.getByRole('button', { name: 'Apply Status' }).click()
  await page.waitForTimeout(600)
  await shot(page, 'c-secrets-confirm')
  const dlg = page.locator('[role=dialog]').last()
  log('confirm dialog', (await dlg.innerText().catch(() => '')).replace(/\s+/g, ' ').slice(0, 200))
  await dlg.getByRole('button').last().click()
  await page.waitForTimeout(1500)
  log('after used:', await msg(page))
  // back to available
  await rows.first().getByRole('checkbox').click().catch(() => {})
  await selectOption(statusTarget, /Available/)
  await page.getByRole('button', { name: 'Apply Status' }).click()
  await page.waitForTimeout(600)
  await page.locator('[role=dialog]').last().getByRole('button').last().click()
  await page.waitForTimeout(1500)
  log('used->available:', await msg(page))
  const card = (await api('GET', `/admin/card-secrets?product_id=13&secret=php`)).data[0]
  log('php card status now', card.status)
  // edit single via API: used -> available
  const e = await api('PUT', `/admin/card-secrets/${card.id}`, { status: 'available' })
  log('PUT used->available', e.status_code, e.msg)
  // export TXT filtered by batch 16 (csv batch)
  await page.getByRole('button', { name: 'Reset' }).first().click()
  await page.waitForTimeout(1000)
  await page.getByPlaceholder('Search batch number').fill((await api('GET', '/admin/card-secrets/batches?product_id=13')).data.find((b) => b.id === 16).batch_no)
  await page.getByRole('button', { name: 'Search', exact: true }).click()
  await page.waitForTimeout(1200)
  log('rows batch filter', await rows.count())
  const scope = page.locator('select').filter({ has: page.locator('option', { hasText: 'Current filtered results' }) })
  await selectOption(scope, 'Current filtered results')
  const [dl] = await Promise.all([page.waitForEvent('download', { timeout: 15000 }), page.getByRole('button', { name: 'Export TXT' }).click()])
  const f = await dl.path()
  log('download', dl.suggestedFilename(), JSON.stringify(fs.readFileSync(f, 'utf8').slice(0, 300)))
  const [dl2] = await Promise.all([page.waitForEvent('download', { timeout: 15000 }), page.getByRole('button', { name: 'Export CSV' }).click()])
  log('download csv', dl2.suggestedFilename(), JSON.stringify(fs.readFileSync(await dl2.path(), 'utf8').slice(0, 300)))
  await shot(page, 'c-secrets-batchfilter')
  // delete php card (selected scope)
  await selectOption(scope, 'Current selection')
  await page.getByRole('button', { name: 'Reset' }).first().click()
  await page.getByPlaceholder('Search secret content').fill('php')
  await page.getByRole('button', { name: 'Search', exact: true }).click()
  await page.waitForTimeout(1200)
  await rows.first().getByRole('checkbox').click()
  await page.getByRole('button', { name: 'Delete Selected' }).click()
  await page.waitForTimeout(600)
  await page.locator('[role=dialog]').last().getByRole('button').last().click()
  await page.waitForTimeout(1500)
  log('delete:', await msg(page), 'stats', JSON.stringify((await api('GET', '/admin/card-secrets/stats?product_id=13')).data))
  // paging
  const all = await api('GET', '/admin/card-secrets?page=1&page_size=5')
  log('paging all', JSON.stringify(all.pagination))
}
