import { dialog, field, selectOption, apiResponse, TS, toast } from './common.mjs'
export default async ({ page, api, shot, log, admin }) => {
  await page.goto(`${admin}/products`)
  await page.waitForLoadState('networkidle')
  await page.getByRole('button', { name: 'Add product' }).click()
  const dlg = dialog(page, 'Add product')
  await dlg.getByRole('tab', { name: 'English', exact: true }).click()
  await field(dlg, 'Product title (English)').fill(`qa-manual ${TS}`)
  await dlg.getByRole('tab', { name: 'Simplified Chinese', exact: true }).click()
  await field(dlg, 'Product title (Simplified Chinese)').fill(`qa-manual ${TS} 人工`)
  await field(dlg, 'Slug (URL identifier)').fill(`qa-manual-${TS}`)
  await selectOption(field(dlg, 'Category', 'select'), /qa-cat 0926$/)
  await selectOption(field(dlg, 'Purchase type', 'select'), 'Guest purchase')
  await selectOption(field(dlg, 'Fulfillment type', 'select'), /Manual/)
  await field(dlg, 'Price amount').fill('3.50')
  await field(dlg, 'Manual remaining stock').fill('20')
  await dlg.getByRole('button', { name: 'Add field' }).click()
  await dlg.getByRole('button', { name: 'Add field' }).click()
  const items = dlg.locator('div', { hasText: /^Field #\d/ }).locator('xpath=ancestor::div[contains(@class,"space-y-3")][1]')
  const f1 = dlg.locator('div.space-y-3', { has: page.getByText('Field #1', { exact: true }) }).last()
  const f2 = dlg.locator('div.space-y-3', { has: page.getByText('Field #2', { exact: true }) }).last()
  await field(f1, 'Field key').fill('account')
  await f1.getByRole('switch').click()
  await field(f1, 'Label (Simplified Chinese)').fill('充值账号')
  await field(f2, 'Field key').fill('region')
  const typeSel = field(f2, 'Field type', 'select')
  log('field types', (await typeSel.locator('option').allTextContents()).join('/'))
  await selectOption(typeSel, /Select|Dropdown/)
  await field(f2, 'Label (Simplified Chinese)').fill('区服')
  await field(f2, 'Options', 'textarea').fill('Asia\nEurope\nAmerica')
  await shot(page, 'c-manual-form')
  const r = await apiResponse(page, 'POST', /\/admin\/products$/, () => dlg.getByRole('button', { name: 'Create now' }).click())
  log('created', JSON.stringify({ id: r.data.id, stock: r.data.manual_stock_total, schema: r.data.manual_form_schema }).slice(0, 900))
  const pub = await page.evaluate(async (s) => (await (await fetch(`/api/v1/public/products/${s}`)).json()), `qa-manual-${TS}`)
  log('public', JSON.stringify({ stock: pub.data?.manual_stock_available, status: pub.data?.stock_status, schema: pub.data?.manual_form_schema }).slice(0, 600))
}
