import { dialog, field, fieldBox, selectOption, apiResponse, TS } from './common.mjs'
export default async ({ page, api, shot, log, admin }) => {
  const code = `QAC${TS}`
  await page.goto(`${admin}/coupons`)
  await page.waitForLoadState('networkidle')
  await page.getByRole('button', { name: 'New coupon' }).click()
  let dlg = dialog(page, 'New coupon')
  await dlg.getByRole('button', { name: 'Save', exact: true }).click()
  await page.waitForTimeout(800)
  log('empty save:', (await page.locator('[role=status]').allInnerTexts()).join(' | '), '| inline:', (await dlg.locator('.text-danger-text').allInnerTexts()).join('/'))
  await field(dlg, 'Code').fill(code)
  await selectOption(field(dlg, 'Type', 'select'), 'Percent')
  await field(dlg, 'Value').fill('150')
  const scope = fieldBox(dlg, 'Applicable products')
  await scope.locator('input').first().fill(`qa-product`)
  await scope.getByRole('button', { name: 'Search products' }).click()
  await scope.getByText(/qa-product 0926/).first().click()
  await dlg.getByRole('button', { name: 'Save', exact: true }).click()
  await page.waitForTimeout(1000)
  log('percent 150 save:', (await page.locator('[role=status]').allInnerTexts()).join(' | '))
  await field(dlg, 'Value').fill('10')
  await field(dlg, 'Min amount').fill('20')
  await field(dlg, 'Max discount').fill('3')
  await field(dlg, 'Usage limit').fill('5')
  await field(dlg, 'Per user limit').fill('1')
  const dts = dlg.locator('input[type="datetime-local"]')
  log('dt inputs', await dts.count())
  await dts.nth(0).fill('2026-09-30T10:00'); await dts.nth(1).fill('2026-09-20T10:00')
  await dlg.getByRole('button', { name: 'Save', exact: true }).click()
  await page.waitForTimeout(1000)
  log('end<start save:', (await page.locator('[role=status]').allInnerTexts()).join(' | '))
  await dts.nth(0).fill('2026-09-20T10:00'); await dts.nth(1).fill('2026-12-31T23:00')
  await shot(page, 'c-coupon-form')
  const r = await apiResponse(page, 'POST', /\/admin\/coupons$/, () => dlg.getByRole('button', { name: 'Save', exact: true }).click())
  log('created', JSON.stringify(r).slice(0, 700))
  await page.waitForTimeout(800)
  await shot(page, 'c-coupon-list')
  // duplicate code
  await page.getByRole('button', { name: 'New coupon' }).click()
  dlg = dialog(page, 'New coupon')
  await field(dlg, 'Code').fill(code.toLowerCase())
  await field(dlg, 'Value').fill('5')
  const scope2 = fieldBox(dlg, 'Applicable products')
  await scope2.locator('input').first().fill(`qa-product`)
  await scope2.getByRole('button', { name: 'Search products' }).click()
  await scope2.getByText(/qa-product 0926/).first().click()
  await dlg.getByRole('button', { name: 'Save', exact: true }).click()
  await page.waitForTimeout(1200)
  log('dup code (lowercase) save:', (await page.locator('[role=status]').allInnerTexts()).join(' | '))
  const list = await api('GET', `/admin/coupons?page=1&page_size=50&code=${code}`)
  log('list by code', list.pagination?.total, JSON.stringify(list.data.map((c) => [c.id, c.code, c.value, c.starts_at, c.ends_at])))
  await dlg.getByRole('button', { name: 'Cancel' }).click().catch(() => {})
}
