import { dialog, field, fieldBox, selectOption, apiResponse, TS } from './common.mjs'
export default async ({ page, api, shot, log, admin }) => {
  await page.goto(`${admin}/promotions`)
  await page.waitForLoadState('networkidle')
  await page.getByRole('button', { name: 'New promotion' }).click()
  const dlg = dialog(page, 'New promotion')
  await field(dlg, 'Name').fill(`qa-promo ${TS}`)
  const typeSel = field(dlg, 'Type', 'select')
  log('types', (await typeSel.locator('option').allTextContents()).join('/'))
  await selectOption(typeSel, /Fixed/)
  await field(dlg, 'Value').fill('30')
  const scope = fieldBox(dlg, 'Applicable product')
  await scope.locator('input').first().fill('qa-product')
  await scope.getByRole('button', { name: 'Search products' }).click()
  await page.waitForTimeout(800)
  await selectOption(scope.locator('select'), /qa-product 0926/)
  await page.waitForTimeout(500)
  log('risk hint:', (await dlg.innerText()).match(/High-risk[\s\S]{0,250}/)?.[0]?.replace(/\s+/g, ' '))
  await shot(page, 'c-promo-risk')
  await selectOption(typeSel, /Percent/)
  await field(dlg, 'Value').fill('20')
  const dts = dlg.locator('input[type="datetime-local"]')
  await dts.nth(0).fill('2026-09-01T00:00'); await dts.nth(1).fill('2026-12-31T00:00')
  const r = await apiResponse(page, 'POST', /\/admin\/promotions$/, () => dlg.getByRole('button', { name: 'Save', exact: true }).click())
  log('created', JSON.stringify(r).slice(0, 500))
  await page.waitForTimeout(800)
  await shot(page, 'c-promo-list')
  const pub = await page.evaluate(async (s) => (await (await fetch(`/api/v1/public/products/${s}`)).json()), `qa-product-${TS}`)
  log('public promo', JSON.stringify({ price: pub.data.price_amount, promo: pub.data.promotion_price_amount, skus: pub.data.skus.map((k) => [k.sku_code, k.price_amount, k.promotion_price_amount]) }))
  // expired window -> should not apply
  const upd = await api('PUT', `/admin/promotions/${r.id}`, { ...r, starts_at: '2026-01-01T00:00:00Z', ends_at: '2026-02-01T00:00:00Z' })
  log('update to past', upd.status_code, upd.msg)
  const pub2 = await page.evaluate(async (s) => (await (await fetch(`/api/v1/public/products/${s}`)).json()), `qa-product-${TS}`)
  log('public after expire', JSON.stringify({ promo: pub2.data.promotion_price_amount, skus: pub2.data.skus.map((k) => [k.sku_code, k.promotion_price_amount]) }))
  const del = await api('DELETE', `/admin/promotions/${r.id}`)
  log('delete promo', del.status_code)
}
