import { admin, user, browser, adminCtx, shot, watch, note, sleep } from './lib.mjs'
const s = await admin('store'); const b = await browser(); const errs = []
const ctx = await adminCtx(b, 'store', s.token); const p = await ctx.newPage(); watch(p, errs)
const net = []; p.on('response', async (r) => { if (r.url().includes('/resellers/') && r.request().method() !== 'GET') net.push(`${r.request().method()} ${new URL(r.url()).pathname} ${r.status()} ${(await r.text().catch(() => '')).slice(0, 250)}`) })
await p.goto('https://store.dot2.com/admin/resellers/profiles'); await sleep(3000)
await shot(p, 'reseller', 'R002-01-profiles', false)
let row = p.locator('tr', { hasText: 'qa-rsl@lab.test' }).first()
console.log('row btns', await row.locator('button').allInnerTexts())
await row.getByRole('button', { name: /通过|审核/ }).first().click(); await sleep(1500)
const dlg = p.locator('[role=dialog]').last(); console.log((await dlg.innerText()).slice(0, 500))
const nums = dlg.locator('input:visible'); const n = await nums.count(); console.log('inputs', await nums.evaluateAll((e) => e.map((x) => x.placeholder + '=' + x.value)))
if (n >= 2) { await nums.nth(0).fill('10'); await nums.nth(1).fill('50') }
await shot(p, 'reseller', 'R002-02-approve-dialog', false)
await dlg.getByRole('button', { name: /^(确认|确定|通过|确认通过)$/ }).last().click(); await sleep(2500)
row = p.locator('tr', { hasText: 'qa-rsl2@lab.test' }).first()
await row.getByRole('button', { name: /拒绝|驳回/ }).first().click(); await sleep(1200)
const d2 = p.locator('[role=dialog]').last(); const ta = d2.locator('textarea:visible, input:visible'); if (await ta.count()) await ta.first().fill('QA 驳回：资料不全')
await d2.getByRole('button', { name: /^(确认|确定|拒绝|驳回|确认拒绝)$/ }).last().click(); await sleep(2500)
await p.reload(); await sleep(2500); await shot(p, 'reseller', 'R002-03-after-review', false)
note('R-002', net.join(' || '))
const u1 = await user('store', 'qa-rsl@lab.test'); note('R-002', 'qa-rsl profile: ' + JSON.stringify((await u1.get('/reseller/profile')).profile).slice(0, 250))
const u2 = await user('store', 'qa-rsl2@lab.test'); const pr = (await u2.get('/reseller/profile')).profile; note('R-003', 'qa-rsl2 after reject: ' + JSON.stringify(pr).slice(0, 250))
const re = await u2.raw('POST', '/reseller/apply', { reason: 'QA 重新申请' }); note('R-003', `reapply: sc=${re.json.status_code} ${re.json.msg} -> ${(await u2.get('/reseller/profile')).profile.status}`)
console.log('ERRS', errs); await b.close()
