import { user, browser, userCtx, shot, watch, note, sleep } from './lib.mjs'
const u = await user('store', 'qa-rsl@lab.test'); const me = await u.get('/me')
const b = await browser(); const errs = []
const ctx = await userCtx(b, u.token, me); const p = await ctx.newPage(); watch(p, errs)
const net = []; p.on('response', async (r) => { if (r.url().includes('/reseller/') && r.request().method() !== 'GET') net.push(`${r.request().method()} ${new URL(r.url()).pathname} ${r.status()} ${(await r.text().catch(() => '')).slice(0, 250)}`) })
await p.goto('https://store.dot2.com/reseller'); await sleep(3000); await shot(p, 'reseller', 'R007-00-dashboard')
await p.goto('https://store.dot2.com/reseller/site'); await sleep(3000)
const ins = await p.locator('main input:visible, main textarea:visible').evaluateAll((e) => e.map((x, i) => `${i}:${x.tagName}:${x.placeholder}:${x.value}`)); console.log(ins.join('\n'))
await shot(p, 'reseller', 'R007-01-site-form')
await p.locator('main input:visible').nth(0).fill('QA 测试分店 · 蓝莓')
await p.locator('main input:visible').nth(1).fill('https://store.dot2.com/admin/favicon.svg')
await p.getByRole('button', { name: /内容/ }).click(); await sleep(1200)
console.log(await p.locator('main input:visible, main textarea:visible, main [contenteditable]:visible').evaluateAll((e) => e.map((x, i) => `${i}:${x.tagName}:${x.placeholder}`)))
const t = p.locator('main textarea:visible, main [contenteditable=true]:visible'); if (await t.count()) await t.first().fill('QA 分店公告：蓝莓味测试')
const chk = p.locator('main [role=switch]:visible, main input[type=checkbox]:visible'); console.log('switches', await chk.count()); if (await chk.count()) await chk.first().click()
await shot(p, 'reseller', 'R007-02-content-tab')
await p.getByRole('button', { name: '保存配置' }).click(); await sleep(3000)
await shot(p, 'reseller', 'R007-03-saved', false)
note('R-007', net.join(' || ').slice(0, 800))
console.log('ERRS', errs); await b.close()
