import { user, browser, userCtx, shot, watch, note, sleep } from './lib.mjs'
const r = await user('store', 'reseller-sakura@lab.test', { register: false }); const me = await r.get('/me')
const b = await browser(); const errs = []; const ctx = await userCtx(b, r.token, me); const p = await ctx.newPage(); watch(p, errs)
const net = []; p.on('response', async (x) => { if (x.url().includes('/reseller/withdraws') && x.request().method() === 'POST') net.push((await x.text()).slice(0, 250)) })
await p.goto('https://store.dot2.com/reseller/withdraws'); await sleep(3000)
await shot(p, 'reseller', 'R016-01-withdraws')
console.log('btns', await p.locator('main button:visible').allInnerTexts())
const dlg = p.locator('body'); console.log((await dlg.innerText()).slice(0, 400)); console.log(await dlg.locator('input:visible, select:visible').evaluateAll((e) => e.map((x) => x.tagName + ':' + x.placeholder)))
await p.locator('input[placeholder="请输入提现金额"]').fill('0.22'); await p.locator('input[placeholder="请输入提现渠道"]').fill('alipay'); await p.locator('input[placeholder="请输入提现账号"]').fill('qa-ui@alipay')
await shot(p, 'reseller', 'R016-02-withdraw-dialog', false)
await dlg.getByRole('button', { name: '提交申请' }).click(); await sleep(1200); await p.getByRole('button', { name: '确认' }).last().click(); await sleep(2500)
await shot(p, 'reseller', 'R016-03-after', false)
note('R-016', 'UI withdraw 0.22: ' + net.join(' || ')); note('R-016', 'balance: ' + JSON.stringify(await r.get('/reseller/balance-accounts')))
console.log('ERRS', errs); await b.close()
